# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='cup',
        ),
        migrations.AddField(
            model_name='character',
            name='games',
            field=models.ManyToManyField(related_name='characters', to='api.Game'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='cups',
            field=models.ManyToManyField(related_name='circuits', to='api.Cup'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='img_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='cup',
            name='img_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
